### ISSUE TITLE
cw_pack_calculate_size function would be nice

### ISSUE THREAD

**Issue by mczarnek** [clwi/CWPack#5]
The one problem I have with this library is that I don't know how to calculate in advance how to calculate how much memory I'll need to allocate here:
    char buffer[20];
    cw_pack_context_init (&pc, buffer, 20, 0);

A really nice function that would maintain the speed of this library but work around this would be a function that allows the user to indicate how many ints they want, how many floats, how many array objects, etc.

I'm thinking:
int cw_pack_calculate_size(int numInts, int numFloats, int numChars, int numBytes, etc...)

And internally it says that an int is of size 4, plus a header of 1(or whatever it is), therefore add numInts * 5 to the size of memory to be allocated, numChars is the number of individual characters across all strings, etc. and at the end it spits out how much memory to allocate before you call cw_pack_context_init.

Thanks for the library and all your work clwi!!

**Comment by clwi** [comment]
Thank you for your interest in CWPack. 

Your proposal is, although very appealing, not possible to implement because one of the features in MessagePack is that as little space as possible is used. E.g. an integer can occupy anything from 1 to 9 bytes depending on the integer.  

Instead I would recommend you to look at _dynamic_memory_pack_context_ defined in goodies/basic-contexts/basic-contexts.h which is especially created to handle this problem.

/Claes

**Comment by mczarnek** [comment]
Thanks Claes. That's a reasonable way to handle it. Personally would be happy if there was such a function that popped out the max size that the Message Pack might be, so that way only one malloc is needed, which is likely higher performance. But as currently, once built, you can determine how large it is. I also suppose this is one reason passing in a struct to compress is nice, behind the scenes you could calculate exactly how much is needed, allocate it then pack it.

Still very useful if memory is cheaper short term than it is once you need to use it, which it typically is. MessagePack is very valuable for storage or networking, but short term.. I'm fine allocating a few extra bytes and value performance.
